name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.12
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.16'
    - name: Install Package & Deps
      run: raco pkg install --batch --auto gui-easy-lib/ gui-easy/
    - name: Test
      run: xvfb-run -a raco test -j "$(nproc)" -p gui-easy-lib
